---
- name: Prepare Local Directory to store operator manifests and DB
  block:
    - name: Prepare Local Directory to store operator manifests
      file:
        path: "{{ local_mirrored_contents_store_dir }}/manifests/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - {{ catalog_sources }}
      register: manifest_dir_created

    - name: Prepare Local Directory to store operator manifest DBs
      file:
        path: "{{ local_mirrored_contents_store_dir }}/manifests-db/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - {{ catalog_sources }}
      register: manifest_db_dir_created

- name: Mirror Catalogs
  command: "{{ oc_cli | default('oc', true) }} adm catalog build --auth-token={{ local_secret_json }} --appregistry-endpoint https://quay.io/cnr --appregistry-org {{ item }} --from='quay.io/operator-framework/operator-registry-server:latest' --to={{ mirror_registry_fqdn_port }}/{{ local_repository }}/{{ item }}:{{ ocp_release }} --manifest-dir={{ local_images_store_dir }}/manifests/{{ item }}/  --to-db={{ local_images_store_dir }}/manifests-db/{{ item }}"
  with_items:
    - {{ catalog_sources }}
  register: operator_catalog_mirrored 
